
services:
  db:
    image: mysql:8
    container_name: staygo_mysql
    environment:
      MYSQL_DATABASE: staygo_progra
      MYSQL_USER: doadmin
      MYSQL_PASSWORD: AVNS_m7RnNCPVaNz6fz2IiPg
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "25060:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: staygo_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/staygo_progra?sslmode=disable
      SPRING_DATASOURCE_USERNAME: doadmin
      SPRING_DATASOURCE_PASSWORD: AVNS_m7RnNCPVaNz6fz2IiPg
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data: